services:
  prometheus:
    image: prom/prometheus            #  ← Prometheus official image
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  ← your config
    ports:
      - "9090:9090"                    # ← Prometheus runs at localhost:9090

  grafana:
    image: grafana/grafana            # ← Grafana official image
    ports:
      - "3000:3000"                     # ← Grafana runs at localhost:3000
    volumes:
      - grafana-storage:/var/lib/grafana  ← persistent dashboard config
    depends_on:
      - prometheus
